### ISSUE TITLE
Social Media and Google Fonts

### ISSUE THREAD

**Issue by ghost** [Really-Simple-Plugins/complianz-gdpr#238]
Hi,
I have two things (little issues) that I noticed.

1) If a website is not using google fonts and host the fonts direct on the server, the assistent find a non existing google fonts service.

2) There is only the option to say yes or no to the social media point. If you choose no, it is not correct and if you choose yes, it does not fit for a shariff solution. 

Thank you so far for offering this good, but not perfect solution. 

Cheers,
Heiko

**Comment by rlankhorst** [comment]
We're looking into the Google Fonts issue. The scan looks for any string in your site's html with fonts.googleapis.com. If it finds a match, you get this suggestion. 

Currently I have trouble finding a theme without GF. Every default WP theme loads the Google Fonts by default. Can I take a look at your site to check what URL the scan might have found? You can also mail me directly: rogier(at)really-simple-ssl.com

As for the social media: The question here is if the social embeds place cookies. Your sharif buttons do not, so you can say "no" here. We'll look at the working to make this more clear.

**Comment by rlankhorst** [comment]
We haven’t found any issues with this, closing.
