### ISSUE TITLE
Changes are not stored in database

### ISSUE THREAD

**Issue by joinso** [Really-Simple-Plugins/complianz-gdpr#284]
This branchs show correctly the values from the database, but any change made in the frontend is not stored.
We have to update the database directly to make changes.
Regards,
Jordi Pujol
JOINSO

**Comment by rlankhorst** [comment]
Hi @joinso,
What changes in the front-end are you referring to?

**Comment by joinso** [comment]
Sorry, when I say "frontend" I refer to the plugin config in Wordpress Administration.
I am refering to change look and feel of the banner, change text, and so on...

Regards,
Jordi Pujol
JOINSO

**Comment by rlankhorst** [comment]
Can you enable debugging by adding to your wp-config.php:

define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true );
define('WP_DEBUG_LOG',     true);

Then post the resulting errors here?

**Comment by joinso** [comment]
Notice: Undefined property: stdClass::$iab_global in /homepages/19/d503012255/htdocs/newSaate/wp-content/plugins/complianz-gdpr/cookiebanner/class-cookiebanner.php on line 258

WordPress database error: [Unknown column 'iab_global' in 'field list']
UPDATE `wp_cmplz_cookiebanners` SET `position` = 'bottom', `banner_version` = '23', `iab_global` = '0', `archived` = '', `title` = '', `theme` = 'classic', `checkbox_style` = 'square', `revoke` = 'Administrar consentimiento', `dismiss` = 'Solo funcionales', `save_preferences` = 'Guardar preferencias', `accept_all` = 'Aceptar todo', `view_preferences` = 'Ver preferencias', `category_functional` = 'Funcional', `category_all` = 'Marketing / Spam Prevention', `category_stats` = 'Estadísticas', `category_prefs` = 'Preferencias', `accept` = 'Aceptar cookies', `message_optin` = '<p>Utilizamos cookies para asegurar que le ofrecemos la mejor experiencia de usuario en nuestro sitio web. Siempre puede ajustar sus preferencias de cookies usando el enlace del pie de página.</p>', `readmore_optin` = 'Política de cookies', `use_categories` = 'hidden', `use_categories_optinstats` = 'hidden', `tagmanager_categories` = '', `hide_revoke` = '0', `banner_width` = '476', `soft_cookiewall` = '0', `dismiss_on_scroll` = '', `dismiss_on_timeout` = '', `dismiss_timeout` = '10', `accept_informational` = 'Acepto', `message_optout` = 'Utilizamos cookies para optimizar nuestro sitio web y nuestro servicio.', `readmore_optout` = 'Cookie Policy', `readmore_optout_dnsmpi` = 'Do Not Sell My Personal Information', `readmore_privacy` = 'Declaración de privacidad', `readmore_impressum` = 'Impressum', `popup_background_color` = '#f1f1f1', `popup_text_color` = '#191e23', `button_background_color` = '#f1f1f1', `slider_background_color` = '#0073aa', `slider_background_color_inactive` = '#F56E28', `slider_bullet_color` = '#fff', `button_text_color` = '#0073aa', `accept_all_text_color` = '#fff', `accept_all_border_color` = '#0073aa', `accept_all_background_color` = '#0085ba', `functional_text_color` = '#0073aa', `functional_border_color` = '#f1f1f1', `functional_background_color` = '#f1f1f1', `border_color` = '#0073aa', `use_custom_cookie_css` = '', `statistics` = 'a:0:{}' WHERE `ID` = 1

**Comment by rlankhorst** [comment]
@joinso thanks for the logs. The problem was a new field in the database, but because the version wasn't bumped to 4.7.3 yet, the database upgrade (which is tied to the version) didn't trigger yet. 

I've now updated the version number. 

Let me know if that helps!

**Comment by joinso** [comment]
So, what I have to do to fix?
Just download this branch again?

Regards,
Jordi Pujol
JOINSO

**Comment by rlankhorst** [comment]
@joinso I've merged that branch as well. If you download the master branch again, the issue should be resolved.

**Comment by joinso** [comment]
Hi, @rlankhorst !
The master branch includes the "pass-lang-parameter-with-ajax-calls" ?
Regards,
Jordi Pujol
JOINSO
