### ISSUE TITLE
An invalid form control with name='cmplz_uses_ad_cookies_personalized' is not focusable.

### ISSUE THREAD

**Issue by joinso** [Really-Simple-Plugins/complianz-gdpr#286]
In the Wizard, Cookies step, that belongs to this url: admin.php?page=cmplz-wizard:
The "Next" doest not work.
This is the error in the browser console:
An invalid form control with name='cmplz_uses_ad_cookies_personalized' is not focusable.

Regards,
Jordi Pujol
JOINSO

**Comment by rlankhorst** [comment]
You're right, due to the TCF update a question required a default setting. This has been fixed now. If you update to the latest branch it should be resolved.
