### ISSUE TITLE
Make Privacy Policy visible

### ISSUE THREAD

**Issue by joinso** [Really-Simple-Plugins/complianz-gdpr#287]
Hi!

The Privacy Policy must be readable without the cookie banner.
To aply this you can setup following this instructions:
https://complianz.io/excluding-pages-from-the-cookie-banner/
This works fine.
But after this, when a new visitor visit the site:

(1) See the banner
(2) Click on Privacy Link : banner is gone.
(3) Click on any other link: 
see this page and banner appears again.

The ideal behaviour is:

(1) See the banner
(2) Click on Privacy Link : 
    **Open in a new window**  and banner is gone.
    Disable all the links in this page: header menu and footer.
    This can be done with jQuery checking if the technical cookis are not allowed.

So if we use "cmplz_edit_cookie_settings" in functions, how can we add the "target='_new' attribute in Privacy Policy link?

Regards,
Jordi Pujol
JOINSO

**Comment by joinso** [comment]
Another problem related to this issue.
If you disable the cookie banner in Privacy Policy, the short codes does not work.
At leas the one related to the choice of the user.
Regards,
Jordi Pujol
JOINSO

**Comment by AertHulsebos** [comment]
Hi @joinso ,

Just to be sure, you're referring to the cookie policy, instead of the privacy policy?

regards Aert

**Comment by joinso** [comment]
This one: $output['readmore_url']['REGION']

The situation is this.
Imagine that you setup the "cookie wall".
The link is shown, is the only one allowed one, and you can go to this link.
However the cookie wall is still there, and you cannot read the page clearly.
The option to exclude this page from cookie banner (https://complianz.io/excluding-pages-from-the-cookie-banner/), is not a good solution, because it makes avalable all the links on this page (header and footer link for example), and also disable the shortcuts of "cookie banner".

After a deeper debug of your code we find a solution that must be a feature in new releases:

Just add this snippet in this page:

<script>
(function($) {
    $(document).on("cmplzCookieWarningLoaded", myScriptHandler);
    function myScriptHandler(consentData) 
    {
            $('#cc-banner-wrap').css("background-color", "rgba(0,0,0,0)");
    }
})(jQuery);
</script>

This make page readable.

Regards,
Jordi Pujol
JOINSO

**Comment by AertHulsebos** [comment]
Hi Jordi,

Concerning the cookie wall. This will be disabled on every page with class cmplz-document in the next update. The rest we will have a look at.

regards Aert

**Comment by joinso** [comment]
Hi, @AertHulsebos !
About this:
"Concerning the cookie wall. This will be disabled on every page with class cmplz-document in the next update"
This is a not good solution (at least for us).
Some behaviours of the "cookie-wall" must be keeped:
- Disable any links.
- Shortcodes must still working.
- The page must be readable: just add my snippet to the documentation, or and option like
"Disable Cookie Wall opacity to some pages"...

Regards,
Jordi Pujol
JOINSO

**Comment by rlankhorst** [comment]
As this is possible with the "hide cookie banner" setting on the page, this can be handled by each website admin himself. As this should resolve the issue, I'll close it for now.
