### ISSUE TITLE
Bad French Translation for Statistics Consent Preferences

### ISSUE THREAD

**Issue by salsa-system** [Really-Simple-Plugins/complianz-gdpr#288]
I'm using Polylang to translate Complianz strings to French. Everything works fine except for the translation of the term "Statistics" displayed in the consent preferences. For some reason the cookie stat consent is translated incorrectly to "Fonctionnel" instead of "Statistiques" as translated in Polylang. It may be a Polylang bug, but it doesn't look like since other cookie consent options (Functional, Marketing) are correctly translated.

![stat-consent-french](https://user-images.githubusercontent.com/11788075/96745344-5676a300-13c6-11eb-93b7-a333c7c7fa0a.png)

**Comment by rlankhorst** [comment]
Hi @salsa-system, this seems to be an issue in combination with Polylang only, we’ve contacted them about this and will get back as soon as we know more.

**Comment by salsa-system** [comment]
thanks for the feedback...I just want to let you know that the issue is fixed... I'm not sure how it was fixed and if it's due to a plugin update? Anyway the Statistics category translation to French is ok now
