### ISSUE TITLE
When cookies are accepted, events with DOMContentLoaded are executed twice

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [Really-Simple-Plugins/complianz-gdpr#295]
Hi,

In a website, we're using some scripts written in Vanilla JavaScript.

We noticed that scripts loaded with a `window.addEventListener('DOMContentLoaded', function(event) {}` are executed twice only if cookies are accepted.

As an example, this code will create two paragraph at the bottom of the page:

```
window.addEventListener('DOMContentLoaded', function(event) {
	var p = document.createElement('p');

	p.innerHTML = 'a paragraph';

	document.body.appendChild(p);
});
```

If the cookies are not accepted, there is no problem.

**Comment by rlankhorst** [comment]
Hi @juliemoynat-tanaguru, 

do you have the contact form 7 integration active? As contact form 7 only fires on the DOM content loaded event, Complianz will run the DomContentLoaded event again after accepting cookies. 

To prevent this you can disable the CF7 integration in complianz/integrations, or you can say "no" on the question if you want to block recaptcha before consent. 

Let me know if that helps!

**Comment by juliemoynat-tanaguru** [comment]
Hi,

Thanks for you answer.

If I understand correctly, I cannot use DOMContentLoaded for my scripts and at the same time require prior consent for RECAPTCHA?

This is a problem…

**Comment by rlankhorst** [comment]
Contact Form 7 cannot work any other way because of the way it's implemented. 

Alternatively, you can use this add on:
https://wordpress.org/plugins/wpcf7-recaptcha/

When  used, the plugin will fall back to another method, which does not require this activation mechanism.

**Comment by juliemoynat-tanaguru** [comment]
Ok, this is not cool but I understand that you can't do anything for this problem.

Thank you for your help.

We found other ideas for the scripts with `DOMContentLoaded`:

- Using `window.addEventListener('load', function (event){}` instead of `window.addEventListener('DOMContentLoaded', function(event) {}` (it must be `window`). It works but it's not really optimized (their is a sort of "jump" of the content in the page).
- Using the document ready function of jQuery if it is already load (this is not really beautiful and I haven't tested it but I think it should work).

**Comment by rlankhorst** [comment]
Hi @juliemoynat-tanaguru, 

If I remember correctly I tried with the document ready of jquery first, but Contact Form 7 doesn't fire it, as the CF7 code does not use jquery. 

Feel free to try alternatives. An easy way to try some things is to disable the CF7 integration in Complianz, then copy over the contact form 7 php file from the integrations/plugins to the mu-plugins folder. 

Then it will work as it works now, and you can adjust it. 

If you encounter e better solution, that would be very welcome!

Together with the WordPress privacy team we developed the WP Consent API, which is a framework that should resolve such issues. If Contact Form 7 would support the WP Consent APi, the problem would be solved. 

We've contacted the developer about it, but he wasn't interested. An additional problem is that CF7 changes the code so often it's hard to maintain the integration.
