### ISSUE TITLE
Uncaught SyntaxError: missing { before function body

### ISSUE THREAD

**Issue by alpargataman** [Really-Simple-Plugins/complianz-gdpr#305]
After installing Complianz 4.9.12 I've found a JavaScript error when I use [WP Google maps](https://es.wordpress.org/plugins/wp-google-maps/) plugin. The error appears on Firefox console as **Uncaught SyntaxError: missing { before function body**.

Checking ways to fix the error I've found some way to fix it, but i'll be good to have it on github for future updates. The file i've modified is [complianz-gdpr/integrations/plugins/wp-google-maps.php](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/master/integrations/plugins/wp-google-maps.php)

I've swtiched line 59 from:
`wp_add_inline_script( 'jquery', "jQuery(document).ready(function($){$script});" );`

To:
`wp_add_inline_script( 'jquery', "jQuery(document).ready(function($){".$script."});" );`

For more information I have Apache 2.4.41, PHP 7.4, WordPress 5.7, Complianz 4.9.12 and WP Google Maps 8.1.11.

**Comment by rlankhorst** [comment]
@alpargataman thanks for reporting the issue. It will be merged, and released in the next update.
