### ISSUE TITLE
do not show cookie banner to googlecrawler 

### ISSUE THREAD

**Issue by Iloivar** [Really-Simple-Plugins/complianz-gdpr#306]
is there a way that the google crawler ignores the cookie banner? This would make sense for SEO reasons. Unfortunately I can't find anything in the settings.
many greetings
Iloivar

**Comment by rlankhorst** [comment]
Hi @Iloivar,

we use the data-nosnippet attribute for this:
https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/e4f5a9a6569e1f3d838b2f1b9b9bd1d0968b4405/assets/js/cookieconsent.js#L244

See also:
https://developers.google.com/search/docs/advanced/crawling/special-tags
