### ISSUE TITLE
find_wordpress_base_path() returns incorrect WP base directory

### ISSUE THREAD

**Issue by ianpegg** [Really-Simple-Plugins/complianz-gdpr#310]
Hello,

This script causes a 500 error when executed in my WP environment. I have placed WP core into its own directory, but have kept wp-config in public_html.

The problem arises as a result of find_wordpress_base_path() traversing the directory structure until it finds wp-config - but when it finds that file it assumes that wp-load will be in the same directory, which it isn't.

The code in question that is causing the issue is on [line 87](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/e8eaa207f92bce1c047cd9a0ec05bf0e89d5e98c/system-status.php#L87). The path that this function returns is then used (starting on [line 11](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/e8eaa207f92bce1c047cd9a0ec05bf0e89d5e98c/system-status.php#L11)) to require wp-load and a few other key scripts from WP core, which causes a fatal error in my case as these scripts are not found.

My suggestion would be to modify the script to use the path specified in ABSPATH and remove the find_wordpress_base_path function entirely as it makes unfounded assumptions about the environment.

Hope this helps!

**Comment by rlankhorst** [comment]
Hi @ianpegg, 

Thanks for reporting the issue. Using ABSPATH is not possible in this case, as this function is used in situations where WordPress is not loaded. The wp-config.php therefore is not loaded either. A solution could be to parse the wp-config.php with a regex for the ABSPATH variable, then retrieve the relative path from there. 

I image the ABSPATH constant contains the relative path in your case, something like:

 define('ABSPATH', dirname(__FILE__) . '/wordpress/');

This wouldn't work if the ABSPATH is defined somewhere else of course. Is the relative path defined in the wp-config.php in your case?

**Comment by rlankhorst** [comment]
@ianpegg I have an idea for a better solution. In the find base path function, if the wp-load.php file is not found, I will iterate through all folders, to search for the wp-load file. This should resolve the issue. I'll get back with a fix soon.

**Comment by rlankhorst** [comment]
@ianpegg I have created a fix here:

https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/find-wp-basepath-in-subdir-installs

Let me know if that works for you. This will get tested, and will get merged in one of the coming updates.

**Comment by ianpegg** [comment]
> Using ABSPATH is not possible in this case, as the find_wordpress_base_path function is used in situations where WordPress is not loaded.

Ah, I had a hunch that might be the case under some circumstances. Understood!

**Comment by ianpegg** [comment]
> @ianpegg I have created a fix here:
> 
> https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/find-wp-basepath-in-subdir-installs
> 
> Let me know if that works for you. This will get tested, and will get merged in one of the coming updates.

Thanks for the speedy fix! I will test this next and get back to you :)

**Comment by ianpegg** [comment]
> @ianpegg I have created a fix here:
> 
> https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/find-wp-basepath-in-subdir-installs
> 
> Let me know if that works for you. This will get tested, and will get merged in one of the coming updates.

Hi Rogier,

I've just tested but I'm getting the following error when I run system status:

`Error: Call to undefined function trailingslashit()`

Outside of the WP environment that function does not exist. Perhaps there is a PHP function that does a similar thing?

**Comment by rlankhorst** [comment]
Hi @ianpegg, of course. I tested the entire function to simulate the subfolder, but did that in the wp environment. I have now removed the trailingslashit function, and double-checked that the system status could now download.

**Comment by ianpegg** [comment]
That seems to have done the job, @rlankhorst - thanks!

The button now generates a txt download with the system environment information.

**Comment by rlankhorst** [comment]
Thanks for confirming!
