### ISSUE TITLE
`class_exists` should not autoload the class

### ISSUE THREAD

**Issue by knomepasi** [Really-Simple-Plugins/complianz-gdpr#315]
https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/ff1e0dcbe5e62d7627489e892e7b861cd0114a7b/functions.php#L2121

When using `class_exists` to check if Complianz is using the Gutenberg editor, autoloading the class isn't necessary. Trying to autoload the class can lead to some unwanted side-effects with third party autoloaders. This can be avoided by passing `false` as the second argument to the function.

**Comment by rlankhorst** [comment]
@knomepasi thanks, didn't know this. I'll adjust the code.

**Comment by AertHulsebos** [comment]
Hi @knomepasi,

Done! Thanks again,
