### ISSUE TITLE
BURP Report SQL Injection

### ISSUE THREAD

**Issue by Ampersander** [Really-Simple-Plugins/complianz-gdpr#317]
Hello,

I'm not good in security so I want to share with you the BURP report of my site with the extension Complianz | GDPR/CCPA Cookie Consent 5.4.0.

**Issue detail**

The cmplz_statistics-anonymous parameter appears to be vulnerable to SQL injection attacks. The payloads 75931905' or 3537=3537-- and 15309448' or 8285=8289-- were each submitted in the cmplz_statistics-anonymous parameter. These two requests resulted in different responses, indicating that the input is being incorporated into a SQL query in an unsafe way.

I don't know if it is a security fail?

**Comment by rlankhorst** [comment]
Hi @Ampersander, 

Thanks for your report. Is this premium or free? And front-end or logged in request? In premium, a consent choice may update consent status in the database if records of consent or a/b testing is enabled. This data is sanitised though. In free, I don't see how this could have any database effect.

**Comment by Ampersander** [comment]
Hi @rlankhorst,

It is the free version with requests made in front-end.
Me too I have no idea may be it is a false positive.

Thank you for the response.

**Comment by rlankhorst** [comment]
There are three Rest API request that can be called from the cookie banner javascript. One is for the manage consent html, which only loads on the cookie policy. One is to load the banner data, and doesn't take any arguments. The last one is the "track_status" method, which only runs when A/B testing is enabled. This one therefore never will get called in the free version. Additionally, each parameter gets sanitised. 

If you have more detailed information on what happens I can investigate that, but based on your info, it seems a false positive.
