### ISSUE TITLE
Documentation link 404

### ISSUE THREAD

**Issue by scheinercc** [Really-Simple-Plugins/complianz-gdpr#323]
On `/wp-admin/admin.php?page=cmplz-script-center` > Script Centre > Whitelist a script, iframe or plugin

> URLs that should be whitelisted. For more information, please read this article.

"article" links to https://complianz.io/script-center#whitelist but I think should link to https://complianz.io/whitelisting-inline-script/

**Comment by rlankhorst** [comment]
Thanks for reporting, will be fixed!
