### ISSUE TITLE
Sometimes the banner does not refresh with the actual consent settings

### ISSUE THREAD

**Issue by antonellon** [Really-Simple-Plugins/complianz-gdpr#324]
I try to describe this little bug for steps
-) After the first consent (an Accept all), reopen the banner to manage cookie consent and click on "View preferences". 
-) Disable (deny) Statistics and Marketing cookies clicking on the two checkboxes. 
At this point, if you click on "Accept all" (instead of "Save preferences") and you reopen the banner without a page refresh, you'll see the checkboxes unsetted, but consents are present and active (because of "Accept all").

Thank you!

**Comment by rlankhorst** [comment]
Hi @antonellon, thanks for reporting, Can you check if this resolves the issue?
https://github.com/Really-Simple-Plugins/complianz-gdpr/compare/accept-/sync?expand=1

**Comment by antonellon** [comment]
Yes, checked. It seems to work fine to me.
Thank you for all!
