### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by paaljoachim** [Really-Simple-Plugins/complianz-gdpr#326]
Hi

I searched Github and discovered this repo with the purpose of testing the newest beta version.
It would be helpful to list the beta version in this list: https://github.com/Really-Simple-Plugins/complianz-gdpr/branches making it easier to download and test. 

I have downloaded and will test the main version here on Github. NB! EDIT: Ahh so I downloaded version 6.0. That was not easy to know before having installed the plugin.

I opened the readme and noticed this:

"At Complianz we are working towards a full-featured privacy suite for all WordPress users to comply with the privacy guideliness for their targeted regions. And we try to make it as easy as possible, while respecting the different guidelines and variability. As privacy is not an easy subject we highly appreciate any feedback, pull requests and issues to further simplify this subject and improve our product, and therefore privacy-friendly websites world-wide and happy users."

First of all I would perhaps do a more step by step procedure. (The following just shows my own basic understanding of privacy.)
1. A very basic privacy overview. User selects type of privacy region - GDPR etc. Selects to either create a new privacy page or use an existing page. Here there could for instance be a link to suggestions for various privacy pages. User sees the following buttons: Accept and Dismiss, and a text link to a privacy page.

2. A more intermediate privacy overview adding in additional areas.

3. Advanced privacy adding in additional areas.

The reason why I write the above is that going through the steps in the wizard to select various options are for some areas more of a guessing game then an educated selection knowing why one selects the options one does. Having a simple approach to get it working would be helpful. One could of course be advised to continue with step 2 when ready to do so. The basic approach should be good enough for basic privacy. (Basic privacy might not cover all aspects that are needed. Which means having information on why to continue with step 2 would be helpful.)

Area that is covered by all steps. Such as customizing the banner. Btw add an option to always show the banner on the frontend of the site. Clicking always show banner on frontend one could see the preview in the backend and also see what it looks like on the frontend. (At the moment I am having a difficult time seeing it on the frontend.)

I will likely edit the above to add in additional information and/or just post additional comments.

**Comment by paaljoachim** [comment]
As I have setup the plugin partly before the Wizard wants me to continue.
I am wondering if there should be a small text link below the button or somewhere in the area that says restart Wizard, so one can either Continue Wizard or restart from the beginning.

![Screenshot 2021-12-31 at 10 10 46](https://user-images.githubusercontent.com/5323259/147814426-22772228-eb07-46e1-8999-ab4c8df2f891.jpg)

There is no way to click the Urgent button to go directly to the specific page. I assume here the focus is on having the user continue with the Wizard.

**Comment by rlankhorst** [comment]
Hi @paaljoachim, thanks for your input. These sound like good suggestions. Reading your comments I think these will be a good fit for our 7.0 update.

The 6.0 update (which is now the master) is focused on restructuring the banner and banner JavaScript, removing jquery and library dependencies, and making the banner faster, even more wcag compatible, and modular.

The 7.0 update will be focused on simplifying things and improving UX in the back-end. Your feedback will be useful particularly in that version.

**Comment by paaljoachim** [comment]
> The 7.0 update will be focused on simplifying things and improving UX in the back-end. Your feedback will be useful particularly in that version.

I look forward to beta testing version 7.0 when the time comes. Thanks!
