### ISSUE TITLE
The Wizard: 1. General -> Security & Consent - not able to click main heading General

### ISSUE THREAD

**Issue by paaljoachim** [Really-Simple-Plugins/complianz-gdpr#328]
For instance when in the Wizard 1.General -> Security & Consent. I am not able to click 1.General and have it automatically select Visitors.

![Screenshot 2021-12-31 at 10 44 09](https://user-images.githubusercontent.com/5323259/147816096-b514b633-8cf3-4828-b4ef-aa71480d304d.jpg)

If one is active in a sub menu such as Security & Consent, the top heading menu such as 1.General as in the above case should be active.  Main headings should be active independent if one clicks these from inside the same submenu or from another submenu.

**Comment by rlankhorst** [comment]
The pointer-events:none is removed:
https://github.com/Really-Simple-Plugins/complianz-gdpr/compare/remove-pointer-events-on-active-heading?expand=1
