### ISSUE TITLE
Create documents screen

### ISSUE THREAD

**Issue by paaljoachim** [Really-Simple-Plugins/complianz-gdpr#331]
I went through the Wizard and I am now on the Create documents screen.

![Screenshot 2021-12-31 at 11 21 52](https://user-images.githubusercontent.com/5323259/147817943-9ffdd6b5-e902-46a4-9710-75fc00e77fef.jpg)

"You can update the page titles here if you want, then click the "Update pages" button." ----> What does this do?

"You haven't selected any legal documents to create. You can skip this step" ---> add punctuation and have skip as an active link. I assume this would be the same as clicking "Save and Continue"

**Comment by rlankhorst** [comment]
Hi @paaljoachim, 

If you click the updates pages button after changing the titles, the titles will be updated on the linked pages. 

-> yes, in this specific case "save and continue" is the same as skip if you do nothing. I'll update the text here.

**Comment by rlankhorst** [comment]
changed in https://github.com/Really-Simple-Plugins/complianz-gdpr/compare/text-change-on-documents-step-in-wizard?expand=1
