### ISSUE TITLE
1 task open - Clicking Continue Wizard starts out at the beginning.

### ISSUE THREAD

**Issue by paaljoachim** [Really-Simple-Plugins/complianz-gdpr#332]
I went through the Wizard and end up having 1 remaining task (perhaps because I did not fill out the website information fields).

![Screenshot 2021-12-31 at 11 27 27](https://user-images.githubusercontent.com/5323259/147818237-d0612c59-88ae-43dd-8c03-2c01b11c71d2.jpg)

This means I have to click the Continue Wizard button. It starts out from the first page. I see a check next to various screens I have already gone through. As there is no check next to the Website information it seems that this is the only page I need to fill out to be finished with all the tasks. It would be helpful if the wizard continued on the remaining task instead of at the beginning.

**Comment by AertHulsebos** [comment]
Hi @paaljoachim,

This is on our backlog. regards Aert

**Comment by paaljoachim** [comment]
Great!
