### ISSUE TITLE
Cookie links don´t have backslash

### ISSUE THREAD

**Issue by Lofesa** [Really-Simple-Plugins/complianz-gdpr#341]
Hi
In the cookie doc generated by the shortcode [cmplz-document type="cookie-statement" region="eu"] there are some mistakes:

File /functions.php:

line 1909   $cookie->slug -> $cookie->slug .'/'
line  1937 http://complianz -> https://complianz

This make links to be redirected

**Comment by rlankhorst** [comment]
@Lofesa thanks, will be fixed in the next update.
