### ISSUE TITLE
Undesired page reload when denying / dismissing cookie banner

### ISSUE THREAD

**Issue by dasisdormax** [Really-Simple-Plugins/complianz-gdpr#342]
Good afternoon.

Today, I updated a wordpress installation to Complianz 6, updated my custom CSS to work as before and stumbled on a very small issue.

After denying cookies, the page is reloaded without an apparent reason. This does not happen when accepting, however.
I tried to disable all integrations and activate the safe mode, but it did not change anything.

In case it helps: I use Complianz to display an Info box about our privacy practices (a consent is not needed for us) and hide all but the "deny" button.

I can work around the problem myself, so this issue is more of an information for you. Thank you very much for creating this useful plugin.

**Comment by rlankhorst** [comment]
Hi @dasisdormax, 

You're correct, this should only happen when the user already accepted marketing cookies. I have created a fix for this. 
https://github.com/Really-Simple-Plugins/complianz-gdpr/compare/only-reload-on-deny-if-marketing-allowed?expand=1

You can test if this works for you. It will also tested by us, and if accepted, merged into the next update.

**Comment by dasisdormax** [comment]
Hello @rlankhorst,

I tested the version and the problem is fixed for me. Thanks.

**Comment by rlankhorst** [comment]
Great, thanks for confirming. This will probably be included in the 6.1 update. Closing this for now.
