### ISSUE TITLE
Is there any reason to limit the width?

### ISSUE THREAD

**Issue by Lofesa** [Really-Simple-Plugins/complianz-gdpr#345]
Hi
In  (assets/css/document.ss line 218) there is a  cmplz-document.max-width: 600px;
This makes text output of the  [cmplz-document type="cookie-statement" region="eu"] only show half screen in desktop devices , this maybe works in movile devices but not  in desktop screen, it show the text using only half screen. When mixed in a page with other text is strange.

Any reason to make this max-width? Why don´t let the theme manage the width of text display?

**Comment by rlankhorst** [comment]
@Lofesa this is done because on some themes, there is no width limitation at all, resulting in a full width legal document. We're currently re-assesing this. For now, you can remove it with some custom css.

**Comment by rlankhorst** [comment]
closing this for now, as it's already on our to do list to re-assess.
