### ISSUE TITLE
document error?

### ISSUE THREAD

**Issue by Lofesa** [Really-Simple-Plugins/complianz-gdpr#346]
Hi
I´ve updated to version 6.1 because  to debug other issue need it.
The in "Cookie policy document" throws a translation error.
Changed cmplz_sprintf by sprintf solved the issue
https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/186924571044e713370eba4c4a6914650340bcb0/config/documents/cookie-policy-eu.php#L10

**Comment by rlankhorst** [comment]
Hi @Lofesa, you're right, I discovered the same thing this afternoon. It was fixed, although in a different way. The cmplz_sprintf catches wrong translations, but, in this case also obsolete arguments. Thanks for reporting.
