### ISSUE TITLE
Cant use shortcode in HTML File

### ISSUE THREAD

**Issue by AlbertMakdissi** [Really-Simple-Plugins/complianz-gdpr#347]
Hello Everyone,

so right now we are in the progress to migrate one of  our wordpress elementor pages, which uses a complianz shortcode for legal matters to a html page. Is it possible to integrate  the shortcode directly into a div for example? 
Thanks in advance.

**Comment by rlankhorst** [comment]
@AlbertMakdissi if it’s pure html, without Wordpress, it won’t work. Complianz always requires Wordpress.

**Comment by AlbertMakdissi** [comment]
@rlankhorst Hi thanks for answering quickly, its a php file with html in it.

**Comment by rlankhorst** [comment]
If the file is rendered by WordPress, you can use the shortcode, otherwise it won't work.

**Comment by AlbertMakdissi** [comment]
So assuming the file is rendered by wordpress. Would I just basically use the shortcode like this e.g.  ?: 
 <div> <?php echo do_shortcode("[shortcode]"); ?></div>

**Comment by rlankhorst** [comment]
Yes, this will work:

`<?php echo do_shortcode('[cmplz-document type="cookie-statement" region="eu"]')?>`

**Comment by AlbertMakdissi** [comment]
text works fine, but the dropdown look like this
![Anmerkung 2022-02-03 160417](https://user-images.githubusercontent.com/96504290/152369056-c641bd6f-9ebc-4679-82fd-b9dd6d2753cc.jpg)
s

**Comment by rlankhorst** [comment]
@AlbertMakdissi that is because the CSS is missing. The css file is added on a wordpress post or page which contains the shortcode. I guess it's not a post or page? You can add the document css with below code:

```
add_action( 'wp_enqueue_scripts', 'cmplz_custom_enqueue_assets'  );
function cmplz_custom_enqueue_assets() {
    wp_register_style( 'cmplz-document', cmplz_url . "assets/css/document$min.css", false, cmplz_version );
    wp_enqueue_style( 'cmplz-document' );
}
```

**Comment by AlbertMakdissi** [comment]
just post it in the same file below the shortcode?

**Comment by rlankhorst** [comment]
You can put it in the same file, as php code.

**Comment by rlankhorst** [comment]
is there a wp_head and wp_footer hook in the file? Otherwise wordpress doesn't know where to put the styles. 

<?php wp_head()?>
<?php wp_footer()?>

**Comment by AlbertMakdissi** [comment]
we are using a get header function in the header and get footer function in the footer. For example:
![grafik](https://user-images.githubusercontent.com/96504290/152533492-a52711b1-2f7c-491a-b382-4fed045c472b.png)

**Comment by codeandflow** [comment]
There was a typo.
We've replaced the "$" with a ".".
Now, it works perfectly. 

Final code:
```
add_action( 'wp_enqueue_scripts', 'cmplz_custom_enqueue_assets'  );
function cmplz_custom_enqueue_assets() {
    wp_register_style( 'cmplz-document', cmplz_url . "assets/css/document.min.css", false, cmplz_version );
    wp_enqueue_style( 'cmplz-document' );
}
```
and
`echo do_shortcode('[cmplz-document type="cookie-statement" region="eu"]')`

Topic closed from our side. Thx for your support!
