### ISSUE TITLE
Integrating FacetWP Maps to be compliant with GDPR

### ISSUE THREAD

**Issue by Idan-noiza** [Really-Simple-Plugins/complianz-gdpr#348]
Hi

We're currently using Complianz Privacy Suite (GDPR/CCPA) premium version 6.0.14 with FacetWP version 3.9.5 and [FacetWP Map](https://facetwp.com/help-center/facets/facet-types/map-facet/) version 0.9.3.

We're facing an issue in turning our standard FacetWP Map implementation into a GDPR compliant one. We would like to put a placeholder instead of the actual map and let FacetWP fire only when the user has given its consent, as documented [here](https://complianz.io/custom-google-maps-implementation/).

The problem is that `cmplz_custom_googlemaps_script` function and `cmplz_dependencies` filter documented in the previous link seem to target a function name as a dependency, and FacetWP Map seem to use an anonymous function as a jQuery event listener callback to initialize Google custom map:

```
$().on('facetwp-loaded', function() {
            FWP_MAP.map = new google.maps.Map(document.getElementById('facetwp-map'), FWP.settings.map.init);
            // more script
}
```
So I'm not sure what kind of dependency I could pass to `cmplz_dependencies` filter

```
function cmplz_custom_maps_dependencies( $tags ) {
	$tags['maps.googleapis.com'] = 'script-that-should-wait';
	return $tags;
}
add_filter( 'cmplz_dependencies', 'cmplz_custom_maps_dependencies' );
```

Maybe that is not an issue and I do not see how to make it work, but is there a way to use Complianz hooks or other kind of implementation to make FacetWP Map initialize on user consent?

**Comment by Idan-noiza** [comment]
Hi @rlankhorst, thank you for answering quickly.

>@Idan-noiza are you sure you need a dependency? often this is not necessary.

I'm sorry that I actually do not know what was referred to as a "dependency", I was just reusing the vocabulary I found on the article about the [Custom Google Maps Implementation](https://complianz.io/custom-google-maps-implementation/).

>2. Make sure the files are loaded correctly after consent
We know “mapOptions” causes an error because it needs the Google API to be loaded. To fix this, we will add **a dependency**. We will tell with the below script that “mapOptions” should wait for the Google API.

I'll be implementing your snippet immediately and give you an immediate feedback about it went.

What I did in the meantime was to put this in functions.php

```
add_filter( 'facetwp_assets', function( $assets ) {
    if ($_COOKIE['cmplz_statistics'] !== "allow") {
        unset($assets["gmaps"]);
        unset($assets["facetwp-map-front"]);
    }
    return $assets;
});
```
In order to prevent any script from FacetWP Map and Google API to be printed on the frontend.

Then, I found out about this `cmplz_fire_categories` event on #336, looking at the code below some diff and added this JavaScript to allow the browser to respond to users' choice
```
document.addEventListener('cmplz_fire_categories', (event) => {
	if (!event.detail.categories.includes('statistics')) {
		if (statistics === true) {
			location.reload();
		}
		statistics = false;
	}
	if (event.detail.categories.includes('statistics')) {
		if (statistics === false) {
			location.reload();
		}
		statistics = true;
	}
});
```
Though it was more of workaround, it helped us imitating the expected cookie compliant behaviour. 

I'll be letting you know about your snippet as soon as I can.

**Comment by rlankhorst** [comment]
Can you share a domain so I can take a look? I generally do not use PHP/server side consent management, as it's not compatible with hard php caching, and a reload is needed after consent, which our fully integrated solutions do not need. But if used, I would recommend to use cmplz_has_consent('statistics') instead of reading the cookie. 

I generally recommend to use this article (paragraph 5):
https://complianz.io/developers-guide-for-third-party-integrations/

In your case it should look something like (please check the comments, can't say if everything is configure correctly):
```
/**
* Add a script to the blocked list
* @param array $tags
*
* @return array
*/
function cmplz_facetwp_script( $tags ) {
  $tags[] = array(
     'name' => 'FacetWP', //id of your map tool
     'category' => 'marketing',
     'urls' => array(
           'maps.googleapis.com', //list of url's to block
          'FWP_MAP.map',
     ),
     'enable_placeholder' => '1',//if the map is not loaded in an iframe, but rendered in a div, set it to 1
     'placeholder' => 'google-maps', //for maps generally ok
     'placeholder_class' => 'mapp-canvas-panel', //if the map is not loaded in an iframe, use a class of the div it's set in here.
     'enable_dependency' => '1',
    'dependency' => [
	    //'wait-for-this-script' => 'script-that-should-wait'. This should reflect the order in which it should load. 
	    'maps.googleapis.com' => 'FWP_MAP.map',
    ],
);

  return $tags;
}
add_filter( 'cmplz_known_script_tags', 'cmplz_facetwp_script' );
```

**Comment by Idan-noiza** [comment]
Hi @rlankhorst, I'm sorry to have kept you waiting. 

> Can you share a domain so I can take a look?

I can share you the domain but the page with the custom google maps map is not public for now, it will be published soon. If you're interested, I can DM you the actual page with the map once it's public.

> I generally recommend to use this article (paragraph 5):
https://complianz.io/developers-guide-for-third-party-integrations/

Thank you! Very interesting documentation, and much easier to find than reading the source code. I might be working on an integration in the future and I'll be more than willing to share once it's functional.

In the meantime, this is what I did.

```
function cmplz_custom_googlemaps_script( $tags ) {
    $tags[] = 'maps.googleapis.com/maps/api/js';
    $tags[] = 'facetwp/assets/js/dist/front.min.js';
    $tags[] = 'facetwp-map-facet/assets/js/front.js';
    return $tags;
}
add_filter( 'cmplz_known_script_tags', 'cmplz_custom_googlemaps_script' );

function cmplz_custom_maps_dependencies( $tags ) {
    $tags['maps.googleapis.com'] = 'facetwp/assets/js/dist/front.min.js';
    $tags['maps.googleapis.com'] = 'facetwp-map-facet/assets/js/front.js';
    return $tags;
}
add_filter( 'cmplz_dependencies', 'cmplz_custom_maps_dependencies' );

function cmplz_custom_maps_placeholder( $tags ) {
    $tags['google-maps'][] = "custom-css-class-for-embed-google-map";
    return $tags;
}
add_filter( 'cmplz_placeholder_markers', 'cmplz_custom_maps_placeholder' );
```
I used those filters in my functions.php. The page now requires less reloading to process successfully the changes of cookie consent by the user.

There was still an issue with the map not showing when the consent for marketing cookies wasn't given initially on page load. The placeholder would then disappear on user's consent to show only a blank space, as FacetWP map seemed to "freeze" the map after is initialization.

So I added this JavaScript, thanks to the event found on the [developer's guide page](https://complianz.io/developers-guide-for-third-party-integrations/) that you communicated earlier, to refresh it on user's consent.

```
function sleep(ms) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

const checkIfFWPExists = async () => {
	if (typeof FWP !== 'undefined' && typeof FWP_MAP !== 'undefined' && typeof FWP_MAP.map !== 'undefined') {
		return true;
	}
	await sleep(1000);
	checkIfFWPExists();
}

const fixMap = async (event) => {
	if (event.detail.category === "marketing") {
		await checkIfFWPExists();
		FWP.loaded = false;
		FWP.refresh();
		document.removeEventListener('cmplz_enable_category', fixMap);
	}
}

document.addEventListener('cmplz_enable_category', fixMap);
```
I had to add a function to check if `FWP_MAP.map` was defined, as it wasn't the case most of the time when the `cmplz_enable_category` fired. Now it works like a charm.

**Comment by rlankhorst** [comment]
Nice!

One note, in this code:

```
    $tags['maps.googleapis.com'] = 'facetwp/assets/js/dist/front.min.js';
    $tags['maps.googleapis.com'] = 'facetwp-map-facet/assets/js/front.js';
```

The last line overwrites the first one. So it won't work for front.min.js. If the condition for the .min file is SCRIPT_DEBUG, you can use:

`$tags['maps.googleapis.com']  = defined('SCRIPT_DEBUG') && SCRIPT_DEBUG ?  'facetwp-map-facet/assets/js/front.js' : 'facetwp/assets/js/dist/front.min.js' ;`

**Comment by rlankhorst** [comment]
@Idan-noiza based on your code, I have created an mu-plugin for the integrations repo, as I would write it:

https://github.com/Really-Simple-Plugins/complianz-integrations/blob/master/facet-wp.php

I will try to get a dev license so we can test it ourselves, and maybe include it in the plugin.

**Comment by Idan-noiza** [comment]
>One note, in this code:
```
$tags['maps.googleapis.com'] = 'facetwp/assets/js/dist/front.min.js';
$tags['maps.googleapis.com'] = 'facetwp-map-facet/assets/js/front.js';
```
>The last line overwrites the first one. So it won't work for front.min.js.

Indeed, thanks for pointing it out.

>@Idan-noiza based on your code, I have created an mu-plugin for the integrations repo, as I would write it:

Really nice! Good to know it will be useful.

Thank you for the good work, and best of luck with everything!

**Comment by Idan-noiza** [comment]
P.S: I forgot to add JavaScript's sleep version source in my previous comment. I edited it.

[Here the source](https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep)

**Comment by rlankhorst** [comment]
Thanks for updating! We've reached out to facetwp as well, to get a dev license to test with.
