### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by jhhazelaar** [Really-Simple-Plugins/complianz-gdpr#352]
Thank you for the great plugin!

Today I came across this repository and I'm wondering if you can create releases tags in de repository? We use composer with Wordpress and that way we can easy install the complainz plugin, but now we install the dev-master with all the latest commits. To insure a stable wordpress installation we need release versions of the plugin.

**Comment by jarno-vos** [comment]
Hi @jhhazelaar,

Thank you for your kind words about the plugin, and for providing your feedback.

Great suggestion. We will consider integrating this (creation of release tags) in our workflow. 

I can't say with certainty from which version this will be done exactly, but in any case, it's on our backlog.

Just let me know if you have any questions about this.

Kind regards,
Jarno
