### ISSUE TITLE
Missing checkout eCommerce events from Woocommerce Google Analytics Integration

### ISSUE THREAD

**Issue by bebjakub** [Really-Simple-Plugins/complianz-gdpr#353]
Hello, 
thanks a lot for this plugin!

I have just one problem after starting using it. There are no tracked sessions with transactions anymore.
![image](https://user-images.githubusercontent.com/10927960/155667996-4bbc9b53-dad8-4c21-929d-fbb221a72bad.png)

We weren't made any changes in the configuration of https://github.com/woocommerce/woocommerce-google-analytics-integration everything worked fine before activating Complianz.

Could you check that, pls?
Thank you!

**Comment by rlankhorst** [comment]
Hi @bebjakub, we'll check this. Until then, you can check if deactivating the integration in complianz/integrations resolves the issue.

**Comment by rlankhorst** [comment]
@bebjakub I just checked this with our integrations developer, and this was reported two weeks ago, and there is a fix ready. We're ready to release it. It will be updated in the master here today. Let me know if that fixes your issue.

**Comment by bebjakub** [comment]
@rlankhorst It works, thanx! :)
