### ISSUE TITLE
script defer in integrations

### ISSUE THREAD

**Issue by Lofesa** [Really-Simple-Plugins/complianz-gdpr#355]
Hi @rlankhorst 

In  /integraion/plugins/lazyloader.php line 21 is this code:
`wp_add_inline_script( 'cmplz-cookiebanner', $script);`
So inline the script with the  cmplz-cookiebanne handler.

In /cookie/class-cookie-admin.php line 1756 is this:

```
public function add_asyncdefer_attribute($tag, $handle) {
                        if ( $handle === 'cmplz-cookiebanner' || $handle === 'cmplz-tcf' ) {
                                return str_replace( '<script ', '<script defer ', $tag );
                        }
                        return $tag;
                }
```

So the defer is added to a inlined snippet withour src attribute.

How can this be solved?

**Comment by Lofesa** [comment]
Hi @rlankhorst 

Tried, the no defer change, it works.

I see in the same  changeset you have deleted the `aria-checked="true"` but not changed vy a `checked` attibute

**Comment by rlankhorst** [comment]
The checked attribute is handled by the JavaScript already.
