### ISSUE TITLE
Wrong Aria Label 

### ISSUE THREAD

**Issue by Lofesa** [Really-Simple-Plugins/complianz-gdpr#356]
Hi @rlankhorst 

`<input type="checkbox" aria-checked="true" id="cmplz-functional-optin" data-category="cmplz_functional" class="cmplz-consent-checkbox cmplz-functional" size="40" value="1">`

Html validators says `aria-checked="true"` is not valid with `input type="checkbox"` .

In https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked is estated that when posible uses `input type` and this not need the `aria-checked="true"`.

Here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-checked say how to use `<input type="checkbox" ` and have it marked by default:

`<input type="checkbox"  checked  id="cmplz-functional-optin" data-category="cmplz_functional" class="cmplz-consent-checkbox cmplz-functional" size="40" value="1">`

**Comment by rlankhorst** [comment]
Yes, I see it. I'll remove it, and it will get merged in one of the coming updates. Thanks for reporting.
