### ISSUE TITLE
Accessibility Errors

### ISSUE THREAD

**Issue by raratiru** [Really-Simple-Plugins/complianz-gdpr#372]
[Achecker](https://achecker.achecks.ca/checker/index.php) reported two errors in our site:

* [input element, type of "checkbox", missing an associated label.](https://achecker.achecks.ca/checker/suggestion.php?id=119)
* [i (italic) element used.](https://achecker.achecks.ca/checker/suggestion.php?id=117)

We fixed them with the following PR: https://github.com/Really-Simple-Plugins/complianz-gdpr/pull/371

**Comment by rlankhorst** [comment]
We've also reviewed the <i> to <em> changes. This does not seem to be an accessibility thing, but more a styling discussion to be made. We'll review if it is better to change to <p style="cmplz-italic"> for example. See 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em for more information about this.

**Comment by raratiru** [comment]
In contrast with the [checker's docs](https://achecker.achecks.ca/checker/suggestion.php?id=117):

> This error will be generated for all i elements.

Mdn clarifies and [elaborates](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em#i_vs._em).

> This means the right one to use depends on the situation. 

It is great to come across those contrasting approaches... 

It feels like a sincere review of the 2020 - 2022 unforgettable period, thank you!
