### ISSUE TITLE
enqueue style sheets

### ISSUE THREAD

**Issue by kingma-sbw** [Really-Simple-Plugins/complianz-gdpr#373]
In a project we need to overide the `.cmplz-cookiebanner .cmplz-links .cmplz-link` class to style the links. Currently the plugin stylesheet is loaded after our main style sheet and nullilying our styles. It seems the styles are not enqueued and hence it is not possible to reorder them with depends[]. 

## Work around:
This style has greater specificity and works in the current version 6.2.4:
```
.cmplz-cookiebanner .cmplz-links a.cmplz-link {}
```

**Comment by rlankhorst** [comment]
This is intentional: These styles are not enqueued in the regular way because they are dynamic: depending on the region, another stylesheet may be required. An additional advantage is that the stylesheet does not delay the site as it only loads after the page has loaded fully.

**Comment by kingma-sbw** [comment]
Understood. And with the small style above we were able to remove it. 
The question remains why the text-decoration: underline is mentioned in the first place. We provide our own links
```
.cmplz-cookiebanner .cmplz-links .cmplz-link {
    color: var(--cmplz_hyperlink_color);
    font-size: var(--cmplz_link_font_size);
    text-decoration: underline;
    margin: 0;
}
```
#

> This is intentional: These styles are not enqueued in the regular way because they are dynamic: depending on the region, another stylesheet may be required. An additional advantage is that the stylesheet does not delay the site as it only loads after the page has loaded fully.
