### ISSUE TITLE
Double slash in Matomo integration script

### ISSUE THREAD

**Issue by quentinqubconsulting** [Really-Simple-Plugins/complianz-gdpr#376]
Hi,

When we use the wizard for the Matomo Tag Manager integration : 
<img width="812" alt="Capture d’écran 2022-09-12 à 16 27 44" src="https://user-images.githubusercontent.com/75498388/189680047-00978834-5ebb-4fd4-aeb0-395a2ce764dc.png">

At the end, there is a double slash in the generated script : 
<img width="1118" alt="Capture d’écran 2022-09-12 à 16 29 39" src="https://user-images.githubusercontent.com/75498388/189680629-b8ea206b-dfce-4af0-bb2f-3f8feb16b8b4.png">

I can't identify the file responsible for generating the Matomo Tag Manager script.

**Comment by AertHulsebos** [comment]
Hi @quentinqubconsulting,

Doesn't 'https://cdn.matomo.cloud/adcdef/responsible-file/ work as entry?

**Comment by quentinqubconsulting** [comment]
Hi,

Same issue with this type of URL : https://cdn.matomo.cloud/adcdef/responsible-file/

Settings in back-office : 
<img width="540" alt="Capture d’écran 2022-09-13 à 01 58 40" src="https://user-images.githubusercontent.com/75498388/189778883-3d6b8bbb-8f1a-46c4-a1e0-0620d4504c22.png">

Result : 
<img width="1231" alt="Capture d’écran 2022-09-13 à 01 57 23" src="https://user-images.githubusercontent.com/75498388/189778910-d2cf00b3-c9e6-4977-9bb4-803198b06131.png">

Of course, with the "double slash", the URL doesn't work.
In Complianz sources, I tried to find the file which is generates the script automatically for delete the excess slash, but I didn't find it.

**Comment by rlankhorst** [comment]
The extra slash has been fixed and will be released in the 6.3 update. This usually doesn't cause any issues, making it purely cosmetic, but perhaps on some servers the server configuration does not allow it.
