### ISSUE TITLE
Any translated versions of the Mo/Po/Pot I could use?

### ISSUE THREAD

**Issue by fredy31** [Really-Simple-Plugins/complianz-gdpr#385]
The docs seem to just talk about translating manually the strings of the plugin.

But thing is, I need to translate in a language that I do not know (Spanish)

So I can't just look at the string in english and simply write it in spanish.

Is there anywhere we can get Mo/Po for other languages?

**Comment by rlankhorst** [comment]
@fredy31 all strings are translated in the WordPress repository. If you start out in Spanish for example, all strings will get set to the defaults in Spanish. So if you change your language to Spanish, then click "reset" in the banner, you will get the Spanish strings. 

Hope this helps.
