### ISSUE TITLE
Jquery conflict on divi theme

### ISSUE THREAD

**Issue by domov44** [Really-Simple-Plugins/complianz-gdpr#390]
Hi,

I am a webmaster and frontend dev for my company.

I noticed an inccompatibility with this extension and my simple jquery code.

jQuery Javasccript :
`	// mobile menu /
(function($) { 
    function setup_collapsible_submenus() {
        // mobile menu
        $('#mobile_menu .menu-item-has-children > a').after('<span class="menu-closed"></span>');
        $('#mobile_menu .menu-item-has-children > a').each(function() {
            $(this).next().next('.sub-menu').toggleClass('hide',1000);
        });
        $('#mobile_menu .menu-item-has-children > a + span').on('click', function(event) {
            event.preventDefault();
            $(this).toggleClass('menu-open');
            $(this).next('.sub-menu').toggleClass('hide',1000);
        });
    }
        
    $(window).load(function() {
        setTimeout(function() {
            setup_collapsible_submenus();
        }, 700);
    });
   
})(jQuery);	
`
Css : 
`/* menu mobile */ 
/********* Mobile Menu Collapse ********/
/* header fixé au scroll */
@media (max-width: 980px){
	.et_fixed_nav #main-header{
		position:fixed;
	}
	}

/* icone menu ouvert */
  .mobile_nav.opened .mobile_menu_bar:before {
    content: '\4d';
}

/* suppression bordure menu ouvert */
.et_mobile_menu li a{
	border-bottom:none;
	color:#151b49;
}

/* stylisation du menu ouvert */
.et_mobile_menu{
	border-top: 3px solid #151b49;
	border-radius:12px;
}

/* écart et centre boutons */
@media (max-width:1023px){
	.menu-item-801, .menu-item-2888{
		display:flex;
		justify-content:center;
		align-items:center;
		margin-top:15px;
		margin-bottom:15px;
	}
}

/**** This hides the sub menu items on mobile ****/
  
#main-header .et_mobile_menu li ul.hide {
display: none !important;
}
  
/**** This adjusts the positioning and the background transparency of the parent menu item on mobile ****/
  
#mobile_menu .menu-item-has-children {
position: relative;
}
#mobile_menu .menu-item-has-children > a {
background: transparent;
}

#mobile_menu a{
	color:#151b49;
}
  
/**** This styles the icon and moves it to the right ****/
  
#mobile_menu .menu-item-has-children > a + span {
position: absolute;
right: 0;
top: 0;
padding: 10px 20px;
font-size: 20px;
font-weight: 700;
cursor: pointer;
z-index: 3;
}
  
/**** Here you can swap out the actual icons ****/
  
span.menu-closed:before {
content: "\3d";
display: block;
color: #151b49;
font-size: 20px;
font-family: ETmodules;
}
  
span.menu-closed.menu-open:before {
content: "\4d";
}
`

When the extension is (tested on 2 website) active the menu looks like this, and the submenus do not open :
![image](https://user-images.githubusercontent.com/102806074/219425603-f372fe88-1bfe-4811-ab5c-ae044934304d.png)

In the console I notice a duplicate <span> tag that shouldn't be there, and isn't there when everything works. 
![image](https://user-images.githubusercontent.com/102806074/219427214-1b271ec1-8ce5-463b-aa7e-a8551128ba4a.png)

Some pictures of a menu that works without the extension :
![image](https://user-images.githubusercontent.com/102806074/219427594-7c38d6ca-e5eb-43e6-aaff-b8e5762eb8c0.png)

Please note:
- This bug has been there since the last update of the extension
- I tested on a local environment under php 7.4.30, and without any extension, just with the code snippet and the latest version of the Divi theme

I hope to have helped you,
Have a good day

**Comment by AertHulsebos** [comment]
Hi @domov44,

Does it work when our Divi integration is off? Under Integrations - Plugins.

If not, with ?cmplz_safe_mode as parameter. 

Setting the integration to off might cause an issue with Google Maps or reCaptcha as an FYI. These need to initialised after consent is granted.

Let me know!

**Comment by rlankhorst** [comment]
The latest version here on GitHub includes an improved Divi integration. Let me know if that works for you!

**Comment by domov44** [comment]
Hi.
I will check it soon
Thanks
