### ISSUE TITLE
Bug Cookie Banner

### ISSUE THREAD

**Issue by sviluppomania** [Really-Simple-Plugins/complianz-gdpr#392]
Hi,
I think there is a bug in the Cookie Banner, although it is "accepted" it reappears every time the page is loaded.

Is there solution?

**Comment by rlankhorst** [comment]
If you post your domain we can take a look. It's usually a JavaScript or minification conflict.

**Comment by sviluppomania** [comment]
www.sviluppomania.com

**Comment by rlankhorst** [comment]
I don't have this issue on your site. After clicking accept, the banner is gone. Reloading or clicking on the site, the banner stays dismissed. Possibly a caching issue in your browser.
