### ISSUE TITLE
wizard - create documents - text is editable in cookie policy field

### ISSUE THREAD

**Issue by rtpHarry** [Really-Simple-Plugins/complianz-gdpr#394]
Not sure what this looks like on the first run, but I just went back to it and noticed that this field is editable:

<img width="1104" alt="image" src="https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/1038062/2f20539e-084e-42fe-b880-95a34b21d83a">

**Comment by rlankhorst** [comment]
Hi @rtpHarry this is intended: you can add the page title here.
