### ISSUE TITLE
wizard - documents - cookie policy inside 

### ISSUE THREAD

**Issue by rtpHarry** [Really-Simple-Plugins/complianz-gdpr#395]
This client is running the free version, I haven't checked this against any paid licences I have.

For this section:

<img width="1098" alt="image" src="https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/1038062/a9e06c3c-32f2-4e67-9db3-432872974c20">

I let the plugin create the cookie policy page on the first run through, but then realised that they have a Cookie Policy section inside the Privacy Policy. 

I've ended up deleting it, but now I don't have a cookie policy link in banner.

In this scenario I want to point it to a #fragment link inside the privacy policy.

It's not clear how I can select the cookie policy to show in the banner, if I manually created a dedicated page, or if I just want to select an existing one.

And if I could do that, it looks like this would have "Privacy Policy" as the clickable text as it only uses the page title with no opportunity to override the anchor text.

**Comment by rlankhorst** [comment]
@rtpHarry I think the easiest solution is to choose a custom URL for the cookie policy, in the general/documents section.
