### ISSUE TITLE
Fix brand names spelling across the plugin

### ISSUE THREAD

**Issue by asafm7** [Really-Simple-Plugins/complianz-gdpr#396]
Youtube -> YouTube
JetPack -> Jetpack
Litespeed -> LiteSpeed

**Comment by AertHulsebos** [comment]
Hi @asafm7,

I have a changed the wording of the brand names, we will push to Github soon. It will be updated next week,

Thanks! regards Aert

**Comment by asafm7** [comment]
@AertHulsebos  I'm realizing that in most cases the brands are also misspelled in cookiedatabase.org, so I hope fixing them won't break the syncing.

**Comment by AertHulsebos** [comment]
Hi @asafm7,

I changed there as well e.g. https://cookiedatabase.org/service/jetpack/ - it doesn't match on name, so this should be fine. Thanks
