### ISSUE TITLE
Consider bypassing cookie-blocker mechanism if consent already given

### ISSUE THREAD

**Issue by asafm7** [Really-Simple-Plugins/complianz-gdpr#397]
I've noticed the cookie-blocker mechanism is being used even if consent is already given (when loading a page with the consent cookie already set).

In my case, it caused an especially clunky experience because of customizations made to the placeholders.

Unless I'm missing something, it might be redundant. This is what I did to bypass it:

```php
add_filter("transient_cmplz_blocked_scripts", 'filter_transient_cmplz_blocked_scripts', 10, 2);

function filter_transient_cmplz_blocked_scripts($cmplz_blocked_scripts, $transient_name) {
    $cmplz_marketing = filter_input(INPUT_COOKIE, 'cmplz_marketing');

    if ($cmplz_marketing === "allow") {
        unset($cmplz_blocked_scripts['open.spotify.com/embed']);
        unset($cmplz_blocked_scripts['youtu.be']);
        unset($cmplz_blocked_scripts['youtube-nocookie.com']);
        unset($cmplz_blocked_scripts['youtube.com']);
        unset($cmplz_blocked_scripts['www.youtube.com/iframe_api']);
    }

    return $cmplz_blocked_scripts;
}
```
Again, unless I'm missing something, you might want to consider bringing something similar into the core.

Thanks for a great plugin!

**Comment by rlankhorst** [comment]
Because a website can be cached, an can have visitors from different regions, the html is always rendered in a blocked state. The content is then unblocked client side.

A positive side effect is that this results in a lazy loading behavior. Third party resources are only loaded after the page has fully loaded.

Hope this explains.

**Comment by asafm7** [comment]
Thanks for the explanation @rlankhorst .

In my case, I bypass cache on all levels if a Complianz cookie is set. So, an unblocked-state can never be cached. If I understand correctly, this leaves only the scenario of someone consenting while being in country X and then moving to country Y with the cookie?

**Comment by rlankhorst** [comment]
Your solution seems fine for your use case. It's just that, because of other caching configurations, we can't integrate this in the plugin itself.

**Comment by asafm7** [comment]
Thanks @rlankhorst .

I'm curious, if I understand correctly, HTML should never be cached if containing personal cookies (such as cookie consent indicators). That means that my setup is actually required.

I understand that even if it is true, you can't count on it, as many won't implement it. Unless there is a way to force bypassing cache, maybe with [nocache_headers()](https://developer.wordpress.org/reference/functions/nocache_headers/). But it probably won't be bulletproof anyway.

Thanks again!
