### ISSUE TITLE
Maybe consider using `wp_get_image_editor()` for converting images to webp and saving

### ISSUE THREAD

**Issue by asafm7** [Really-Simple-Plugins/complianz-gdpr#402]
Have you considered using `wp_get_image_editor()` for converting to webp and saving?

I've been using it for Spotify placeholders and it seems more straightforward than using native PHP functions, but I might be missing something.

It basically handled by two lines:
        
```php
$image = wp_get_image_editor($oembed_thumbnail_url);

$image->save($image_path, 'image/webp');
```

It seems to automatically convert any format to webp, so no checks are required.

You can handle errors with:

```php
if (!is_wp_error($image)) {
    // Something
}
```

**Comment by rlankhorst** [comment]
@asafm7 I have added in our beta7.0 branch for testing:
https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/react

**Comment by asafm7** [comment]
@rlankhorst Great. I will have a look.
