### ISSUE TITLE
Complianz with Out of the Block: OpenStreetMap

### ISSUE THREAD

**Issue by n-langle** [Really-Simple-Plugins/complianz-gdpr#405]
Hi,

First of all, thanks for your plugin. It is very useful.

We detected an error with 'Out of the Block: OpenStreetMap'.
If OpenStreetMap is blocked in Complianz settings, with or without user consent, the map isn't displayed.
It's seems, only few scripts of ootb-openstreetmap are blocked, what causing a js error.

WordPress: 5.9.7
Complianz Privacy Suite (GDPR/CCPA) premium multisite: 6.4.3
[Out of the Block: OpenStreetMap](https://github.com/gsarig/ootb-openstreetmap): 2.4.0

Best regards

**Comment by rlankhorst** [comment]
Hi @n-langle, 
There is currently no integration with this plugin. We will add it to our roadmap. Alternatively, there are several other OpenStreetMap plugins which work out of the box with Complianz. 

Additionally, you can ask the developers to integrate with Complianz or more generically, with the WP Consent API, from their side, which is sometimes the only way, depending on how it's developed: 
https://complianz.io/developers-guide-for-third-party-integrations/

**Comment by n-langle** [comment]
Thanks  @rlankhorst
