### ISSUE TITLE
Cookies are still loaded even if we refuse them

### ISSUE THREAD

**Issue by pulsarinformatique** [Really-Simple-Plugins/complianz-gdpr#408]
On https://www.fonds-metro.org/ even if we refuse the cookies we still have many cookies loaded :

![image](https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/10794564/9119bc5b-a4e1-41a7-8379-c97804b9e5fb)

what did we miss ?

if these cookies are mandatories can we know their purpose exactly please?
thanks

cyril

**Comment by pulsarinformatique** [comment]
Thanks
I'm a bit surprised : you wrote all these cookies are functional but some of them have names such as statistics or marketing :


cmplz_functional
cmplz_statistics
cmplz_marketing
cmplz_consented_services
cmplz_policy_id
cmplz_preferences
cmplz_banner-status

For each of them we need their real purpose, functional or marketing category and retention duration please

Besides how can we set their duration to 6 months only instead of the current 1 year duration please ?

thanks

**Comment by rlankhorst** [comment]
For example the cookie cmplz_marketing is functional, because the purpose is to store if marketing/tracking consent is given. Not to do tracking itself. This means that the purpose of the cookie is purely functional, while  it's value can give other services consent to do marketing tracking.

**Comment by pulsarinformatique** [comment]
thanks

but for each of them we need their real description please

Besides how can we set their duration to 6 months only instead of the current 1 year duration please ?

thanks

**Comment by rlankhorst** [comment]
https://cookiedatabase.org/?s=Cmplz&lang=en

Here you can find all cookies used by Complianz

**Comment by rlankhorst** [comment]
You can set the expiration in the general settings.

**Comment by pulsarinformatique** [comment]
thanks

**Comment by pulsarinformatique** [comment]
Hi
is it a bug that some complianz plugins are marked as 'incomplete' in the plugin please ?

![image](https://github.com/Really-Simple-Plugins/complianz-gdpr/assets/10794564/76163b80-e58b-4eab-a285-7a1bedb78d92)

Thanks
