### ISSUE TITLE
Issue with Forminator

### ISSUE THREAD

**Issue by Kirov-B** [Really-Simple-Plugins/complianz-gdpr#415]
Hello, we have an issue together with Forminator Pro, it triggers a fatal error  

Cannot override final method Forminator_Addon_Abstract::get_instance() in /var/www/vhosts/liefit.li/httpdocs/wp-content/plugins/complianz-gdpr/integrations/plugins/forminator-addon-class.php on line 45

Thanks.

**Comment by rlankhorst** [comment]
As this is only a registration of the integration within Forminator, I think the easiest way to resolve this is to drop that registration. The integration itself is not affected. Can you check if this works for you?
https://github.com/Really-Simple-Plugins/complianz-gdpr/tree/forminator

**Comment by Kirov-B** [comment]
This works. Thanks.

**Comment by rlankhorst** [comment]
@Kirov-B Forminator just contacted us, they will revert the change that caused the issue on the next update.

So we won't merge this branch, but you have a solution until then with it.
