### ISSUE TITLE
Enhancement: Improve "cmplz_document_elements" filter functionality

### ISSUE THREAD

**Issue by huubl** [Really-Simple-Plugins/complianz-gdpr#423]
**Description:**
I believe the "[cmplz_document_elements](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/master/config%2Fclass-config.php#L375)" filter needs some improvements to increase its utility:

1. The filter currently works only in MU-plugins, limiting usability. It should function in regular plugins and themes as well.

2. All [document elements](https://github.com/Really-Simple-Plugins/complianz-gdpr/blob/master/config%2Fdocuments%2Fcookie-policy-eu.php) should have named keys (like 'contact-details-2'), so they can be targeted for customization.

See: [WordPress Support Topic](https://wordpress.org/support/topic/filter-cmplz_document_elements-not-working/)

**Why:**
The 'cmplz_document_elements' filter provides more granular control over specific sections of the document, allowing for targeted customization. This approach is more efficient and less error-prone than modifying the entire HTML output with 'cmplz_document_html'.

**Example usage:**
```php
function mod_cmplz_dynamic_document_elements($elements, $region, $type, $fields) {
    if (isset($elements['contact-details-2']['content'])) {
        $elements['contact-details-2']['content'] = 'override contact details HTML';
    }
    return $elements;
}
add_filter('cmplz_document_elements', __NAMESPACE__ . '\\mod_cmplz_dynamic_document_elements', 99, 4);
```

**Comment by AertHulsebos** [comment]
Hi @huubl Thanks. We're having a look!

**Comment by AertHulsebos** [comment]
Hi @huubl We're changing the legal document structure fully in 8.0, which will be this year. I would propose you either fork it and create your own for now. We are in code freeze on document HTML and related functions now. Thanks Aert
